### PR TITLE
Input and output handling with ConsoleHandler

### PR DESCRIPTION
**Pull request by Friedinger**

### CODE REVIEW

**Comment by Friedinger** [comment]
Erste Versuche für den Input

**Review by Massakaboy — APPROVED** [review]
Looks good!

**Comment by IamPekka058** [comment]
Returns "Code input successful. Please wait, analyzing..." for input "". I would implement an if query to check if an input is empty.

**Comment by Friedinger** [comment]
Just added your suggestion

**Review by IamPekka058 — APPROVED** [review]
👍

**Pull request merged**
